# Generated by Django 5.2.4 on 2026-01-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_product_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
