# Generated by Django 5.2.4 on 2026-02-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='subcategory',
        ),
    ]
