# Generated by Django 5.2.4 on 2026-02-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_remove_product_subcategory_delete_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
