# Generated by Django 5.2.4 on 2026-02-19 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_price',
            new_name='Item_price',
        ),
    ]
