# Generated by Django 5.2.4 on 2026-03-23 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
