# Generated by Django 5.2.4 on 2026-03-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_userstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
